import Head from "next/head";
import { useState,useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Bagbox from "../Components/Bagbox";
import Loader from "@/Components/loader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [data, setdata] = useState(null)
    
    const fetchdata = async () =>{
        let data = await fetch(`/api/getproducts`).then(a=>{
            return a.json()
        }).then(a=> {
            setdata(a)
            sessionStorage.setItem('data',JSON.stringify(a))
        })
    }

    useEffect(() => {
      if (typeof window !== 'undefined') {
        const savedData = sessionStorage.getItem('data');
        if (savedData) {
          setdata(JSON.parse(savedData))
        }
        else{
          fetchdata()
        }
      }
      if(!data){
        fetchdata()
        }
    
    }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <div className={styles.home}>
        <div className={styles.left}>
          <h1>New Arrivals</h1>
          
          <br></br><Link href="/shop">Browse Shop &rarr;</Link>
        </div>
        <div className={styles.right}>
          {/* <img className={styles.homeimg} src="https://i.etsystatic.com/21162700/r/il/a26648/4314612039/il_570xN.4314612039_pio8.jpg"></img> */}
        </div>
      </div>


      <h1 className={styles.bagshead}>Latest Arrivals</h1>
      <div className={styles.bags}>
        {data ? data.slice(0,8).map((e)=>{
          return <Link href={`/shop/${e._id}`} key={e._id} >
            <Bagbox price={e.price} title={e.title} image={e.image}></Bagbox>
            </Link>
        }) : <Loader />}
      </div>
    </>
  );
}
